language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $sansi_travis_token
  local_dir: public
  keep_history: true
  on:
    branch: master