language: node_js
node_js:
  - "11.14.0"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - echo 'hesamkaveh.com' > ./public/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $sansi_travis_token
  local_dir: public
  keep_history: true
  on:
    branch: master